Add PlayerController compose ui
jizaher/PoPoCast pull request #1
Opened 2020-11-20 08:57 UTC by dev-weiqi

- 新增 PlayerController 
- 新增 PlayerViewModel

![demo](https://user-images.githubusercontent.com/55677874/99779919-c0fb3a00-2b50-11eb-96cf-bd93a71df494.gif)

2020-11-20 09:37 UTC, lush-life commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +                        style = PoPoCastTypography.subtitle1,
[Suggestion] 可用 `MaterialTheme.typography.subtitle1` 取當前 theme 的 typography

2020-11-20 09:37 UTC, lush-life commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +                        style = PoPoCastTypography.subtitle2,
[Suggestion] 可用 MaterialTheme.typography.subtitle2 取當前 theme 的 typography

2020-11-20 09:45 UTC, AmyPlace requested changes
done

2020-11-20 09:45 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/widget/EllipsisText.kt
> +        text = AnnotatedString(text),
[建議]可以不用包AnnotatedString

2020-11-20 09:45 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/MainActivity.kt
> +                    PlayerController()
[建議]可以在 player 裡面寫個 preview function 做顯示

2020-11-20 15:28 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +                        style = PoPoCastTypography.subtitle1,
done

2020-11-20 15:28 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +                        style = PoPoCastTypography.subtitle2,
done

2020-11-20 15:29 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/widget/EllipsisText.kt
> +        text = AnnotatedString(text),
done

2020-11-20 15:29 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/MainActivity.kt
> +                    PlayerController()
預覽怪怪的，直接拔掉

2020-11-23 01:47 UTC, AmyPlace approved these changes

2020-11-23 01:59 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +    }
突然發現是不是少了一個 progressBar?

2020-11-23 02:06 UTC, HsienDaDa commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +                        color = Color.White,
既然要將color定義在color.kt供人參考使用
那這邊這個也開一個來用吧
不然日後會變成要跑兩個地方修改color惹

2020-11-23 02:21 UTC, ivanisidrowu approved these changes

2020-11-23 13:16 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +    }
加上去囉！

2020-11-23 13:16 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/player/PlayerController.kt
> +                        color = Color.White,
done!

2020-11-24 02:03 UTC, lush-life approved these changes

2020-11-24 02:24 UTC, HsienDaDa approved these changes

2020-11-24 02:54 UTC, merged