Add compose ui for channel page (version 1)
jizaher/PoPoCast pull request #3
Opened 2020-11-24 08:20 UTC by AmyPlace

- 先上第一版的 channel 畫面
- 未完成
-- 收合 toolbar
-- sticky header (所有章節)
-- channel 介紹資訊的展開與收合

![device-2020-11-24-161550](https://user-images.githubusercontent.com/43088818/100066807-76d7c880-2e70-11eb-9a18-ac46afa852f9.png)

2020-11-24 08:27 UTC, HsienDaDa commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +    Column(modifier = Modifier.fillMaxSize().background(Color.Black)) {
Colors.black

2020-11-24 08:28 UTC, HsienDaDa commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +                    tint = Color.White
Colors.white

2020-11-24 08:30 UTC, HsienDaDa commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +                    end.linkTo(parent.end)
parent是不是也有right?
若不考慮RTL的話是不是用 parent.right?

2020-11-24 08:54 UTC, dev-weiqi reviewed
Done

2020-11-24 08:54 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +                border = BorderStroke(1.dp, Color.White),
1dp 要寫在dimens嗎？

2020-11-24 08:54 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/channel/Item.kt
> +                color = Color.LightGray,
好像滿多color沒寫在colors裡面

2020-11-24 09:03 UTC, ivanisidrowu requested changes

2020-11-24 09:03 UTC, ivanisidrowu commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +data class ChannelInfo(
這個要不要獨立一個 class 會比較好？

2020-11-24 09:03 UTC, ivanisidrowu commented on app/src/main/java/tw/jizah/popocast/ui/channel/Item.kt
> +        backgroundColor = Color.DarkGray
可以使用 Colors 裡面的

2020-11-24 09:03 UTC, ivanisidrowu commented on app/src/main/java/tw/jizah/popocast/ui/channel/Item.kt
> +        backgroundColor = Color.DarkGray
下面的顏色也有類似的狀況，所以我就不留言了

2020-11-24 09:03 UTC, ivanisidrowu commented on app/src/main/res/values/strings.xml
> +    <string name="all_chapter">所有章節</string>
我們是統一寫英文還是統一寫中文？  還是要先做 localization?

2020-11-24 09:35 UTC, AmyPlace commented on app/src/main/res/values/strings.xml
> +    <string name="all_chapter">所有章節</string>
決議先支援英文跟繁中

2020-11-24 09:36 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +                    end.linkTo(parent.end)
決議不使用 left/right

2020-11-24 10:44 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +                    tint = Color.White
done

2020-11-24 10:44 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +                border = BorderStroke(1.dp, Color.White),
done

2020-11-24 10:44 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Item.kt
> +                color = Color.LightGray,
done

2020-11-24 10:45 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +data class ChannelInfo(
done

2020-11-24 10:45 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Item.kt
> +        backgroundColor = Color.DarkGray
done

2020-11-24 10:45 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
> +    Column(modifier = Modifier.fillMaxSize().background(Color.Black)) {
done

2020-11-24 10:51 UTC, dev-weiqi approved these changes

2020-11-24 10:53 UTC, HsienDaDa approved these changes

2020-11-25 02:07 UTC, ivanisidrowu approved these changes
🤘🏼

2020-11-25 02:14 UTC, lush-life approved these changes

2020-11-25 03:21 UTC, merged