Add the first version of the search page.
jizaher/PoPoCast pull request #4
Opened 2020-11-24 08:43 UTC by ivanisidrowu

- screenshot: https://drive.google.com/file/d/1jnYNO90ukA8Yi1nnL7ddW41U9lmZmIEH/view?usp=sharing

### TODO
- Click listeners
- Adapters
- ViewModels

2020-11-24 09:08 UTC, AmyPlace requested changes
Done

2020-11-24 09:08 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/search/SearchPage.kt
> +                .preferredSize(60.dp)
60.dp 可以放在 Dimens 中

2020-11-24 09:56 UTC, dev-weiqi approved these changes

2020-11-24 09:56 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/theme/Colors.kt
> +    val grey = Color(0xFF808080)
Nit: 這個 grey 要不要拿上面定義的 50-900 相近的來用就好

2020-11-24 10:22 UTC, lush-life approved these changes

2020-11-25 01:52 UTC, AmyPlace approved these changes
👍

2020-11-25 01:59 UTC, ivanisidrowu commented on app/src/main/java/tw/jizah/popocast/ui/theme/Colors.kt
> +    val grey = Color(0xFF808080)
ok

2020-11-25 02:45 UTC, HsienDaDa reviewed
有個習慣你自己要想一下到底要用哪套
引用Colors or Dimens時
到底是否要完整 Colors.black/Dimens.m1
還是要 black/m1?

目前你是混著寫的情況

2020-11-25 02:45 UTC, HsienDaDa approved these changes

2020-11-25 02:47 UTC, merged