Add episode detail page
jizaher/PoPoCast pull request #7
Opened 2020-11-25 11:02 UTC by lush-life

1. 新增單集資訊頁
2. 加入 kotlinx.datetime lib

尚未完成：
1. AppBar 收合動畫
2. 單集介紹
- 展開動畫
- 支援 html 格式
5. 播放狀態
6. 單集圖片

畫面：
![device-2020-11-25-184720](https://user-images.githubusercontent.com/12621026/100219208-abbb4c80-2f50-11eb-9a93-e8ecee979926.png)
![device-2020-11-25-184751](https://user-images.githubusercontent.com/12621026/100219244-b37af100-2f50-11eb-9b96-308d4f85734b.png)

2020-11-25 12:20 UTC, dev-weiqi approved these changes

2020-11-25 12:20 UTC, dev-weiqi commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
>                              TimeUnit.DAYS
Nit: 這邊要用 `kotlinx-datetime-jvm` 幫他改寫一下嗎 🤓

2020-11-25 14:37 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/channel/Channel.kt
>                              TimeUnit.DAYS
這個鍋我之後再改 XD

2020-11-26 01:57 UTC, ivanisidrowu requested changes

2020-11-26 01:57 UTC, ivanisidrowu commented on app/src/main/java/tw/jizah/popocast/ui/theme/Colors.kt
> +    val greenA700 = Color(0xFF1DB954)
多一個 A 是 typo 嗎？

2020-11-26 02:06 UTC, lush-life commented on app/src/main/java/tw/jizah/popocast/ui/theme/Colors.kt
> +    val greenA700 = Color(0xFF1DB954)
AXXX 也是其中一種色階的命名
https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=82B1FF

2020-11-26 02:08 UTC, ivanisidrowu approved these changes

2020-11-26 02:19 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/episode/EpisodeDetail.kt
> +    val iconTint = Color.White
[Q] Color.White => Colors.white

2020-11-26 02:19 UTC, AmyPlace commented on app/src/main/java/tw/jizah/popocast/ui/episode/EpisodeDetail.kt
> +@Composable
[Q] 這個是不是不用 @Composable

2020-11-26 02:25 UTC, lush-life commented on app/src/main/java/tw/jizah/popocast/ui/episode/EpisodeDetail.kt
> +    val iconTint = Color.White
Done.

2020-11-26 02:25 UTC, lush-life commented on app/src/main/java/tw/jizah/popocast/ui/episode/EpisodeDetail.kt
> +@Composable
Done.

2020-11-26 02:26 UTC, AmyPlace approved these changes
👍

2020-11-26 02:47 UTC, HsienDaDa commented on app/src/main/java/tw/jizah/popocast/ui/episode/EpisodeDetail.kt
> +    var minutes = if (period.seconds > 0) {
是不是用這個來算時分秒比較快呢～
`
    val hours = TimeUnit.MILLISECONDS.toHours(durationInMillis)
    val minutes = TimeUnit.MILLISECONDS.toMinutes(durationInMillis)
    val seconds = TimeUnit.MILLISECONDS.toSeconds(durationInMillis)
`

2020-11-26 03:16 UTC, lush-life commented on app/src/main/java/tw/jizah/popocast/ui/episode/EpisodeDetail.kt
> +    var minutes = if (period.seconds > 0) {
改成先算有餘秒則 duration 直接加一分鐘

2020-11-26 03:24 UTC, HsienDaDa approved these changes

2020-11-26 04:20 UTC, merged